exclude:
  - CONTRIBUTING.md
  - README.md
  - TERMS.md
  - todo.md
  - front
  - node_modules
  - bower_components
  - usptostrap
  - bower.json
  - package.json
  - LICENSE


baseurl: "/designpatterns"
homeurl: "/designpatterns"

permalink: /:title
markdown: kramdown

kramdown:
  auto_ids: true
  parse_block_html: true

defaults:
  - scope:
      path: ""
    values:
      layout: "pattern"

email: contactUXD@uspto.gov?subject=USPTO UI Design Library
repository:
  name: uspto/designpatterns
  url: https://github.com/uspto/designpatterns

version: 1.0.0
versions:
  - name: 1.0.0
    url: /designpatterns/1.0.0/docs
  - name: future
    url: /designpatterns/docs

doctypes:
  - foundation
  - components
  - patterns
